### ISSUE TITLE
Training not working: FileNotFoundError

### ISSUE THREAD

**Issue by AtillaKaanAlkan** [shon-otmazgin/lingmess-coref#3]
Hi @shon-otmazgin ,

After having tested FastCoref last week, this time, I am trying to train LingMess model on my corpus. 

I prepared as required my `my_train_corpus.jsonlines`, `my_dev_corpus.jsonlines` and `my_test_corpus.jsonlines` corpora.

However when I run the following command: 
```

python run.py \
       --output_dir=lingmess-tdac \
       --overwrite_output_dir \
       --model_name_or_path=biu-nlp/lingmess-coref \
       --train_file=my_train_corpus.jsonlines \
       --dev_file=my_dev_corpus.jsonlines \
       --test_file=my_test_corpus.jsonlines \
       --max_tokens_in_batch=5000 \
       --do_train \
       --eval_split=dev \
       --logging_steps=500 \
       --eval_steps=1000 \
       --train_epochs=129 \
       --head_learning_rate=3e-4 \
       --learning_rate=1e-5 \
       --ffnn_size=2048 \
       --experiment_name="lingmess-tdac" \
       --device=cuda:0
```
I receive the following error message: 

```
File "/kaggle/working/lingmess-coref/coref_dataset.py", line 72, in create
    dataset = datasets.load_from_disk(dataset_path)
  File "/opt/conda/lib/python3.10/site-packages/datasets/load.py", line 1742, in load_from_disk
    raise FileNotFoundError(f"Directory {dataset_path} not found")
FileNotFoundError: Directory cache/eef1be7206ecaa2c52d2f952977ad196 not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/kaggle/working/lingmess-coref/run.py", line 131, in <module>
    main()
  File "/kaggle/working/lingmess-coref/run.py", line 82, in main
    dataset, dataset_files = coref_dataset.create(
  File "/kaggle/working/lingmess-coref/coref_dataset.py", line 85, in create
    dataset = dataset.map(encode, batched=False, fn_kwargs={'tokenizer': tokenizer})
  File "/opt/conda/lib/python3.10/site-packages/datasets/dataset_dict.py", line 438, in map
    {
  File "/opt/conda/lib/python3.10/site-packages/datasets/dataset_dict.py", line 439, in <dictcomp>
    k: dataset.map(
  File "/opt/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 1955, in map
    return self._map_single(
  File "/opt/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 520, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 487, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/datasets/fingerprint.py", line 458, in wrapper
    out = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2320, in _map_single
    example = apply_function_on_filtered_inputs(example, i, offset=offset)
  File "/opt/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2220, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 1915, in decorated
    result = f(decorated_item, *args, **kwargs)
  File "/kaggle/working/lingmess-coref/coref_dataset.py", line 52, in encode
    encoded_example = _tokenize(tokenizer, example['tokens'], example['clusters'], example['speakers'])
  File "/kaggle/working/lingmess-coref/coref_dataset.py", line 33, in _tokenize
    assert tokens[start:end + 1] == new_tokens[token_to_new_token_map[start]:token_to_new_token_map[end] + 1]
TypeError: can only concatenate str (not "int") to str
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /kaggle/working/lingmess-coref/coref_dataset.py:72 in create                 │
│                                                                              │
│    69 │   dataset_path = os.path.join(cache_dir, cache_key)                  │
│    70 │                                                                      │
│    71 │   try:                                                               │
│ ❱  72 │   │   dataset = datasets.load_from_disk(dataset_path)                │
│    73 │   │   logger.info(f'Dataset restored from: {dataset_path}')          │
│    74 │   except FileNotFoundError:                                          │
│    75 │   │   logger.info(f'Creating dataset for {dataset_files}')           │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/datasets/load.py:1742 in             │
│ load_from_disk                                                               │
│                                                                              │
│   1739 │   │   dest_dataset_path = dataset_path                              │
│   1740 │                                                                     │
│   1741 │   if not fs.exists(dest_dataset_path):                              │
│ ❱ 1742 │   │   raise FileNotFoundError(f"Directory {dataset_path} not found" │
│   1743 │   if fs.isfile(Path(dest_dataset_path, config.DATASET_INFO_FILENAME │
│   1744 │   │   return Dataset.load_from_disk(dataset_path, fs, keep_in_memor │
│   1745 │   elif fs.isfile(Path(dest_dataset_path, config.DATASETDICT_JSON_FI │
╰──────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: Directory cache/eef1be7206ecaa2c52d2f952977ad196 not found

During handling of the above exception, another exception occurred:

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /kaggle/working/lingmess-coref/run.py:131 in <module>                        │
│                                                                              │
│   128                                                                        │
│   129                                                                        │
│   130 if __name__ == "__main__":                                             │
│ ❱ 131 │   main()                                                             │
│   132                                                                        │
│                                                                              │
│ /kaggle/working/lingmess-coref/run.py:82 in main                             │
│                                                                              │
│    79 │   logger.info(f'Parameters: {t_params + h_params:.1f}M, Transformer: │
│    80 │                                                                      │
│    81 │   # load datasets                                                    │
│ ❱  82 │   dataset, dataset_files = coref_dataset.create(                     │
│    83 │   │   tokenizer=tokenizer,                                           │
│    84 │   │   train_file=args.train_file, dev_file=args.dev_file, test_file= │
│    85 │   │   cache_dir=args.cache_dir                                       │
│                                                                              │
│ /kaggle/working/lingmess-coref/coref_dataset.py:85 in create                 │
│                                                                              │
│    82 │   │                                                                  │
│    83 │   │   dataset = DatasetDict(dataset_dict)                            │
│    84 │   │   logger.info(f'Tokenize documents...')                          │
│ ❱  85 │   │   dataset = dataset.map(encode, batched=False, fn_kwargs={'token │
│    86 │   │   dataset = dataset.remove_columns(column_names=['speakers', 'cl │
│    87 │   │                                                                  │
│    88 │   │   logger.info(f'Saving dataset to {dataset_path}')               │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/datasets/dataset_dict.py:438 in map  │
│                                                                              │
│    435 │   │   if cache_file_names is None:                                  │
│    436 │   │   │   cache_file_names = {k: None for k in self}                │
│    437 │   │   return DatasetDict(                                           │
│ ❱  438 │   │   │   {                                                         │
│    439 │   │   │   │   k: dataset.map(                                       │
│    440 │   │   │   │   │   function=function,                                │
│    441 │   │   │   │   │   with_indices=with_indices,                        │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/datasets/dataset_dict.py:439 in      │
│ <dictcomp>                                                                   │
│                                                                              │
│    436 │   │   │   cache_file_names = {k: None for k in self}                │
│    437 │   │   return DatasetDict(                                           │
│    438 │   │   │   {                                                         │
│ ❱  439 │   │   │   │   k: dataset.map(                                       │
│    440 │   │   │   │   │   function=function,                                │
│    441 │   │   │   │   │   with_indices=with_indices,                        │
│    442 │   │   │   │   │   with_rank=with_rank,                              │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py:1955 in    │
│ map                                                                          │
│                                                                              │
│   1952 │   │   disable_tqdm = not logging.is_progress_bar_enabled()          │
│   1953 │   │                                                                 │
│   1954 │   │   if num_proc is None or num_proc == 1:                         │
│ ❱ 1955 │   │   │   return self._map_single(                                  │
│   1956 │   │   │   │   function=function,                                    │
│   1957 │   │   │   │   with_indices=with_indices,                            │
│   1958 │   │   │   │   with_rank=with_rank,                                  │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py:520 in     │
│ wrapper                                                                      │
│                                                                              │
│    517 │   │   else:                                                         │
│    518 │   │   │   self: "Dataset" = kwargs.pop("self")                      │
│    519 │   │   # apply actual function                                       │
│ ❱  520 │   │   out: Union["Dataset", "DatasetDict"] = func(self, *args, **kw │
│    521 │   │   datasets: List["Dataset"] = list(out.values()) if isinstance( │
│    522 │   │   for dataset in datasets:                                      │
│    523 │   │   │   # Remove task templates if a column mapping of the templa │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py:487 in     │
│ wrapper                                                                      │
│                                                                              │
│    484 │   │   │   "output_all_columns": self._output_all_columns,           │
│    485 │   │   }                                                             │
│    486 │   │   # apply actual function                                       │
│ ❱  487 │   │   out: Union["Dataset", "DatasetDict"] = func(self, *args, **kw │
│    488 │   │   datasets: List["Dataset"] = list(out.values()) if isinstance( │
│    489 │   │   # re-apply format to the output                               │
│    490 │   │   for dataset in datasets:                                      │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/datasets/fingerprint.py:458 in       │
│ wrapper                                                                      │
│                                                                              │
│   455 │   │   │                                                              │
│   456 │   │   │   # Call actual function                                     │
│   457 │   │   │                                                              │
│ ❱ 458 │   │   │   out = func(self, *args, **kwargs)                          │
│   459 │   │   │                                                              │
│   460 │   │   │   # Update fingerprint of in-place transforms + update in-pl │
│   461                                                                        │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py:2320 in    │
│ _map_single                                                                  │
│                                                                              │
│   2317 │   │   │   │   )                                                     │
│   2318 │   │   │   │   if not batched:                                       │
│   2319 │   │   │   │   │   for i, example in enumerate(pbar):                │
│ ❱ 2320 │   │   │   │   │   │   example = apply_function_on_filtered_inputs(e │
│   2321 │   │   │   │   │   │   if update_data:                               │
│   2322 │   │   │   │   │   │   │   if i == 0:                                │
│   2323 │   │   │   │   │   │   │   │   buf_writer, writer, tmp_file = init_b │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py:2220 in    │
│ apply_function_on_filtered_inputs                                            │
│                                                                              │
│   2217 │   │   │   │   additional_args += (effective_indices,)               │
│   2218 │   │   │   if with_rank:                                             │
│   2219 │   │   │   │   additional_args += (rank,)                            │
│ ❱ 2220 │   │   │   processed_inputs = function(*fn_args, *additional_args, * │
│   2221 │   │   │   if update_data is None:                                   │
│   2222 │   │   │   │   # Check if the function returns updated examples      │
│   2223 │   │   │   │   update_data = isinstance(processed_inputs, (Mapping,  │
│                                                                              │
│ /opt/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py:1915 in    │
│ decorated                                                                    │
│                                                                              │
│   1912 │   │   │   │   │   Example(item, features=self.features) if not batc │
│   1913 │   │   │   │   )                                                     │
│   1914 │   │   │   │   # Use the LazyDict internally, while mapping the func │
│ ❱ 1915 │   │   │   │   result = f(decorated_item, *args, **kwargs)           │
│   1916 │   │   │   │   # Return a standard dict                              │
│   1917 │   │   │   │   return result.data if isinstance(result, LazyDict) el │
│   1918                                                                       │
│                                                                              │
│ /kaggle/working/lingmess-coref/coref_dataset.py:52 in encode                 │
│                                                                              │
│    49 def encode(example, tokenizer):                                        │
│    50 │   if 'clusters' not in example:                                      │
│    51 │   │   example['clusters'] = []                                       │
│ ❱  52 │   encoded_example = _tokenize(tokenizer, example['tokens'], example[ │
│    53 │                                                                      │
│    54 │   gold_clusters = encoded_example['gold_clusters']                   │
│    55 │   encoded_example['num_clusters'] = len(gold_clusters) if gold_clust │
│                                                                              │
│ /kaggle/working/lingmess-coref/coref_dataset.py:33 in _tokenize              │
│                                                                              │
│    30 │                                                                      │
│    31 │   for cluster in clusters:                                           │
│    32 │   │   for start, end in cluster:                                     │
│ ❱  33 │   │   │   assert tokens[start:end + 1] == new_tokens[token_to_new_to │
│    34 │                                                                      │
│    35 │   encoded_text = tokenizer(new_tokens, add_special_tokens=True, is_s │
│    36                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
TypeError: can only concatenate str (not "int") to str

```

However, when I replace, my `my_train_corpus.jsonlines`, `my_dev_corpus.jsonlines` and `my_test_corpus.jsonlines` files by a .jsonlines file generated with the inference step (described in README.MD) the training works. So, I am not understanding why it does not work when I give my own jsonlines files (despite the files being in the same path and having the same entries etc.). Did you already encounter that issue?

Thank you very much for you help!

Best,
Atilla

**Comment by AtillaKaanAlkan** [comment]
I solved it, I am closing the issue.
